### ISSUE TITLE
Linkify breaking at web urls with @ in them

### ISSUE THREAD

**Issue by deathg0d** [SoapBox/linkifyjs#76] opened 2015-07-21 13:10 UTC
Some links nowadays have @ in them. For example: https://medium.com/@ainiesta/how-instagram-closed-my-account-and-gave-it-to-a-football-celebrity-625a6a770eb3 or http://naya.com.np/@mandala/post/5b62ff340a9451b3bdda9d89be5c61be

Linkify ignores everything after @

**Comment by nfrasser** [comment] 2015-07-21 20:44
This is a duplicate of #33 and has already been fixed in 2.0.

**Closed by nfrasser** 2015-07-21 20:44 UTC
