### ISSUE TITLE
Strings that contain a double quote get added as part of the link

### ISSUE THREAD

**Issue by maherbeg** [SoapBox/linkifyjs#80] opened 2015-09-11 21:17 UTC
If a string with a url part contains a double quote character, then linkify will add that in as part of the URL.

Example
```javascript
linkifyStr('https://helloworld.com/test"')
"<a href="https://helloworld.com/test&quot;" class="linkified" target="_blank">https://helloworld.com/test"</a>"
```

Is this expected behavior? I've found an easy work around using `formatHref` but this is slightly strange. Example use cases are a URL in a JSON string that is rendered as a `<pre>` block.

**Comment by nfrasser** [comment] 2015-11-12 21:37
I couldn't reproduce this. I tried running `linkifyStr('https://helloworld.com/test"')` in the console here http://soapbox.github.io/linkifyjs/ and got back the string `<a href="https://helloworld.com/test" class="linkified" target="_blank">https://helloworld.com/test</a>"`

**Comment by nfrasser** [comment] 2015-11-12 21:50
Note that Linkify depends primarily on whitespace delimiters to tell where a URL ends, and whether to include the characters following the URL

For example:

This https://helloworld.com/test","hi is a link

Here, the `","hi` part is included in the anchor tag because there is no white space between the commas and quotes (which can actually be part of a URL - there's a bit of underlying ambiguity here).

However, in the following case

https://helloworld.com/test" is a link

We ignore the quote because it precedes whitespace, which is a sign that it's a delimiter, not part of the URL.

Generally, I do not recommend using Linkify for parsing languages like JSON that do not rely on whitespace.

**Comment by maherbeg** [comment] 2015-11-13 00:00
Is that page using `2.0.0-beta.4` ?

I just tried this and it outputted the incorrect value.
```
maher@st-maher1 ~/Downloads> npm install 'linkifyjs@2.0.0-beta.4'
linkifyjs@2.0.0-beta.4 node_modules/linkifyjs
└── jquery@1.11.3
maher@st-maher1 ~/Downloads> node
> var linkifyStr = require('linkifyjs/string')
undefined
> linkifyStr('http://helloworld.com/test"')
'<a href="http://helloworld.com/test&quot;" class="linkified" target="_blank">http://helloworld.com/test"</a>'
```

**Comment by nfrasser** [comment] 2015-11-13 00:03
Ah, my mistake, it's using an older version that did once implement this properly. In that case, a fix for this will definitely be issued.

**Closed** 2015-12-15 03:34 UTC
